name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: Pytest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.4
    - name: Set up Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.9
    - name: Install Python dependencies
      run: python -m pip install pytest scipy numpy hypothesis
    - name: Run tests
      run: pytest
